Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 1024
      Handler: com.serverless.Handler
      CodeUri: C:\Users\pablo\Projects\julio-exercicio
      Runtime: java8.al2
      Architectures:
        - x86_64