Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 1152
      Handler: com.serverless.Handler
      CodeUri: C:\Users\Micro\Documents\estudo\projetos\java-lambda-login-api
      Runtime: java11
      Architectures:
        - x86_64